services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data/data_store:/data/data_store
    command: python3 /home/autogen/autogen/myapp/main.py
